(() => {
 'use strict';
 const $=s=>document.querySelector(s),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const clone=x=>JSON.parse(JSON.stringify(x)),bi=(zh='',en='')=>({zh,en});let data=clone(window.SITE_CONTENT),tab='profile',dirty=false,busy=false,photoLang='zh',selected=new Set(),timer;
 data.papers.forEach((p,i)=>{p.order??=i;p.pinned=!!p.pinned});data.photos.forEach((p,i)=>{p.camera??={focal:'',iso:'',shutter:'',aperture:''};p.featured=!!p.featured;if(p.featured)p.featuredOrder??=i});
 const names={experience:'个人经历',mentors:'导师信息',honors:'荣誉获奖',undergraduate:'本科阶段',graduate:'硕士阶段'};
 const value=path=>path.split('.').reduce((o,k)=>o?.[k],data);
 function mark(){dirty=true;$('#dirty').textContent='有未导出的修改'}
 function set(path,v){const keys=path.split('.');let o=data;for(const k of keys.slice(0,-1))o=o[k];o[keys.at(-1)]=v;mark()}
 function field(path,label,multi=false,wide=false){return `<label class="field ${wide?'wide':''}"><span>${esc(label)}</span>${multi?`<textarea data-path="${path}" rows="3">${esc(value(path))}</textarea>`:`<input data-path="${path}" value="${esc(value(path))}">`}</label>`}
 const pair=(path,label,multi=false)=>`<fieldset class="bilingual"><legend>${esc(label)}</legend><div class="form-grid">${field(path+'.zh','中文',multi)}${field(path+'.en','English',multi)}</div></fieldset>`;
 const title=(text,action='')=>`<div class="editor-panel-title"><h2>${text}</h2>${action}</div>`;
 const add=(path)=>`<button class="button" data-add="${path}">＋ 添加</button>`;
 const paperIndexes=(first,pin)=>data.papers.map((p,i)=>({p,i})).filter(x=>x.p.first===first&&(pin===undefined||x.p.pinned===pin)).sort((a,b)=>Number(b.p.pinned)-Number(a.p.pinned)||(a.p.order??a.i)-(b.p.order??b.i)).map(x=>x.i);
 function controls(path,i,paper=false){const list=paper?paperIndexes(data.papers[i].first,data.papers[i].pinned):value(path).map((_,j)=>j),pos=list.indexOf(i);return `<div class="record-actions">${paper?`<button class="button pin-toggle ${data.papers[i].pinned?'is-pinned':''}" data-pin="${i}" aria-pressed="${data.papers[i].pinned}">${data.papers[i].pinned?'★ 取消置顶':'☆ 置顶'}</button>`:''}<button class="button triangle" data-move="${path}.${i}" data-direction="-1" aria-label="上移" ${pos===0?'disabled':''}>▴</button><button class="button triangle" data-move="${path}.${i}" data-direction="1" aria-label="下移" ${pos===list.length-1?'disabled':''}>▾</button><button class="button remove" data-remove="${path}.${i}">删除</button></div>`}
 function record(path,i,label,body,paper=false){return `<article class="editor-card ${paper&&data.papers[i].pinned?'pinned-editor':''}" data-record="${path}.${i}"><div class="record-header"><h3>${esc(label)}</h3>${controls(path,i,paper)}</div><details><summary>展开编辑</summary><div>${body}</div></details></article>`}
 function profile(){const p=data.profile;return title('基本信息')+pair('profile.name','姓名')+`<div class="form-grid">${['birth','phone','wechat','github','email'].map((key,i)=>field('profile.'+key,['出生年月','电话','微信号','GitHub 主页','邮箱'][i])).join('')}</div>`+['affiliation','degree','intro','research'].map((k,i)=>pair('profile.'+k,['院校','专业与身份','个人简介','研究方向'][i],i>1)).join('')+`<section class="editor-section">${title('研究标签',add('profile.tags'))}${p.tags.map((x,i)=>`<div class="compact-record"><div class="form-grid">${field(`profile.tags.${i}.zh`,'中文')}${field(`profile.tags.${i}.en`,'English')}</div><button class="button remove" data-remove="profile.tags.${i}" aria-label="删除研究标签">删除</button></div>`).join('')}</section><section class="editor-section">${title('生活照路径',add('profile.portraits'))}${p.portraits.map((x,i)=>`<div class="compact-record">${field('profile.portraits.'+i,'照片 '+(i+1)+' · 相对路径或 URL')}<button class="button remove" data-remove="profile.portraits.${i}" aria-label="删除生活照">删除</button></div>`).join('')}</section>`}
 function paperForm(i){const p=data.papers[i],path='papers.'+i;return `<div class="form-grid">${field(path+'.title','论文标题',true,true)}<label class="field wide"><span>作者（英文逗号分隔）</span><textarea data-authors="${i}">${esc(p.authors.map(a=>a.name+a.marks).join(', '))}</textarea></label>${field(path+'.date','首次公开日期（YYYY-MM-DD）')}<label class="field"><span>论文类别</span><select data-first="${i}"><option value="true" ${p.first?'selected':''}>第一作者 / 共同第一作者</option><option value="false" ${!p.first?'selected':''}>合作论文 / 非第一作者</option></select></label></div>${pair(path+'.summary','论文介绍',true)}${pair(path+'.status','发表状态')}<div class="form-grid">${field(path+'.project','Project page URL')}${field(path+'.arxiv','arXiv URL')}${field(path+'.openreview','OpenReview URL')}${!p.image.startsWith('data:')?field(path+'.image','代表图路径 / URL'):''}</div>${pair(path+'.figure','图片说明')}<label class="file-label">替换代表图<input type="file" accept="image/jpeg,image/png,image/webp" data-paper-image="${i}"></label>${p.image?`<img src="${esc(p.image)}" alt="论文代表图">`:''}`}
 function papers(){return title('论文管理')+`<p class="note">* 第一 / 共同第一作者，† 通讯作者，‡ 通讯作者兼项目负责人。点击“置顶”会将论文移到所属类别前列并突出显示；可置顶多篇，使用 ▴ ▾ 调整置顶论文之间或普通论文之间的顺序。</p>`+[true,false].map(first=>`<section class="editor-section">${title((first?'第一作者 / 共同第一作者':'合作论文 / 非第一作者')+' · '+paperIndexes(first).length,`<button class="button" data-add-paper="${first}">＋ 添加论文</button>`)}${paperIndexes(first).map(i=>record('papers',i,data.papers[i].title||'新论文',paperForm(i),true)).join('')}</section>`).join('')}
 function records(path){const list=value(path),label=names[path.split('.').at(-1)]||names[path]||path;return `<section class="editor-section">${title(label,add(path))}${list.map((r,i)=>{const p=path+'.'+i;let body='';if(path==='experience')body=pair(p+'.title','院校 / 机构')+pair(p+'.date','时间')+pair(p+'.detail','说明',true);else if(path==='mentors')body=pair(p+'.name','姓名')+pair(p+'.role','身份')+pair(p+'.description','研究方向与简介',true)+field(p+'.url','主页链接',false,true);else body=field(p+'.date','时间')+pair(p+'.title','获奖名称')+pair(p+'.detail','说明',true)+(r.team?pair(p+'.team','团队',true):'');return record(path,i,r.title?.zh||r.name?.zh||'新条目',body)}).join('')}</section>`}
 function groups(){const map=new Map();data.photos.forEach((p,i)=>{const key=p.year+'|'+p.theme.zh;if(!map.has(key))map.set(key,{year:p.year,theme:p.theme,items:[]});map.get(key).items.push(i)});return [...map.values()].sort((a,b)=>b.year.localeCompare(a.year)||(a.theme.zh==='西藏风光'?-1:b.theme.zh==='西藏风光'?1:0))}
 const options=()=>groups().map((g,i)=>`<option value="${i}">${esc(g.year)} · ${esc(g.theme.zh)}</option>`).join('');
 function destination(prefix){return `<div class="form-grid"><label class="field wide"><span>选择已有类别 / 新建类别</span><select id="${prefix}-theme"><option value="new">＋ 新建类别</option>${options()}</select></label><label class="field"><span>年份</span><input id="${prefix}-year" value="${new Date().getFullYear()}" inputmode="numeric"></label><label class="field"><span>主题（中文）</span><input id="${prefix}-zh"></label><label class="field"><span>Theme (English)</span><input id="${prefix}-en"></label></div>`}
 function photos(){const pinned=data.photos.filter(p=>p.featured).length;return title(`摄影作品 · 已置顶 ${pinned} 张`,`<div class="language-segment"><button data-photo-lang="zh" class="${photoLang==='zh'?'active':''}">中文</button><button data-photo-lang="en" class="${photoLang==='en'?'active':''}">English</button></div>`)+`<p class="note">点击每张照片右上角的“置顶轮播”即可加入摄影页顶部轮播；取消后会立即移出。轮播按首次置顶顺序播放。</p><details class="upload-box"><summary>＋ 添加照片</summary><div>${destination('upload')}<label class="field"><span>单张体积上限</span><select id="photo-size"><option value="3000000">3 MB · 优先清晰度</option><option value="1000000">1 MB · 更快加载</option></select></label><label class="file-label">选择图片（可多选）<input id="photo-files" type="file" accept="image/jpeg,image/png,image/webp" multiple></label><p class="small muted">自动读取可用拍摄参数，生成带年份的配色水印；参数可手动补充。</p></div></details><div class="batch-toolbar"><label class="check"><input id="select-all" type="checkbox" ${data.photos.length&&selected.size===data.photos.length?'checked':''}>全选</label><span id="selected-count">已选 ${selected.size} 张</span><button class="button" id="batch-move" ${selected.size?'':'disabled'}>移动到…</button><button class="button remove" id="batch-delete" ${selected.size?'':'disabled'}>批量删除</button></div>${groups().map(g=>`<section class="photo-editor-group"><div class="group-caption"><label class="check"><input type="checkbox" data-select-group="${esc(g.items.join(','))}" ${g.items.every(i=>selected.has(data.photos[i].id))?'checked':''}>${esc(g.year)} · ${esc(g.theme[photoLang]||g.theme.zh)}</label><span>${g.items.length} 张</span></div>${g.items.map(i=>{const p=data.photos[i],path='photos.'+i;return `<article class="photo-editor-row ${p.featured?'featured-photo-editor':''}"><div class="photo-thumb"><input type="checkbox" data-select-photo="${esc(p.id)}" aria-label="选择 ${esc(p.title.zh)}" ${selected.has(p.id)?'checked':''}><img src="${esc(p.src)}" alt="${esc(p.title.zh)}" loading="lazy"></div><div><div class="photo-row-actions"><button class="button pin-toggle ${p.featured?'is-pinned':''}" data-photo-pin="${i}" aria-pressed="${p.featured}">${p.featured?'★ 取消置顶':'☆ 置顶轮播'}</button></div><div class="form-grid">${field(path+'.title.'+photoLang,photoLang==='zh'?'作品名':'Title')}${field(path+'.alt.'+photoLang,photoLang==='zh'?'图片描述':'Alt text')}</div><div class="camera-fields">${['focal','iso','shutter','aperture'].map((k,n)=>field(path+'.camera.'+k,['焦距','ISO','S · 快门','f · 光圈'][n])).join('')}</div></div></article>`}).join('')}</section>`).join('')}`}
 function render(){const open=[...document.querySelectorAll('[data-record]')].filter(e=>e.querySelector('details')?.open).map(e=>e.dataset.record);document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('#editor-panel').innerHTML=tab==='profile'?profile():tab==='papers'?papers():tab==='photos'?photos():tab==='honors'?title('荣誉获奖')+records('honors.graduate')+records('honors.undergraduate'):tab==='stats'?title('浏览与爱心统计接口')+field('stats.endpoint','读取访客统计 URL')+field('stats.visitEndpoint','记录访问 URL')+field('stats.likesEndpoint','读取照片爱心 URL')+field('stats.likeEndpoint','照片点爱心 URL')+'<p class="note">访客读取接口返回 {"uniqueVisitors":123}；爱心读取接口返回各照片数量与当前访客已点赞列表。所有接口都需要允许当前站点跨域访问。</p>':records(tab);open.forEach(key=>{const e=[...document.querySelectorAll('[data-record]')].find(x=>x.dataset.record===key);if(e)e.querySelector('details').open=true})}
 function toast(s){$('#editor-status').textContent=s;$('#editor-status').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('#editor-status').classList.remove('show'),4500)}
 function move(path,i,delta){const a=value(path);if(path==='papers'){const ids=paperIndexes(a[i].first,a[i].pinned),pos=ids.indexOf(i),j=ids[pos+delta];if(j===undefined)return;[ids[pos],ids[pos+delta]]=[j,i];ids.forEach((id,n)=>a[id].order=n)}else{if(i+delta<0||i+delta>=a.length)return;[a[i],a[i+delta]]=[a[i+delta],a[i]]}mark();render()}
 function addRecord(path){let r;if(path==='profile.tags')r=bi();else if(path==='profile.portraits')r='';else if(path==='experience')r={title:bi(),date:bi(),detail:bi()};else if(path==='mentors')r={name:bi(),role:bi(),description:bi(),url:''};else r={date:'',title:bi(),detail:bi(),team:bi()};value(path).push(r);mark();render();const e=[...document.querySelectorAll('[data-record]')].find(e=>e.dataset.record===path+'.'+(value(path).length-1));if(e){e.querySelector('details').open=true;e.scrollIntoView({block:'center'})}}
 function destinationValue(prefix){const year=$('#'+prefix+'-year').value.trim(),zh=$('#'+prefix+'-zh').value.trim(),en=$('#'+prefix+'-en').value.trim()||zh;if(!/^\d{4}$/.test(year)||!zh)throw Error('请填写四位年份和中文主题');return {year,theme:bi(zh,en)}}
 function validate(){if(!data.profile.name.zh.trim())throw Error('请填写姓名');for(const p of data.papers){if(!p.title.trim())throw Error('请填写论文标题');if(!/^\d{4}-\d{2}(-\d{2})?$/.test(p.date))throw Error('论文日期请使用 YYYY-MM-DD 或 YYYY-MM');for(const k of ['project','arxiv','openreview'])if(p[k]&&!/^https?:\/\//i.test(p[k]))throw Error('论文链接应以 https:// 开头')}for(const p of data.photos)if(!/^\d{4}$/.test(p.year)||!p.theme.zh.trim())throw Error('请填写照片年份与主题')}
 function setBusy(on){busy=on;document.querySelectorAll('.editor-actions button,.editor-tabs button').forEach(b=>b.disabled=on)}
 async function syncPhotos(){for(const p of data.photos)if(p.baseSrc&&p.watermarkYear!==p.year)Object.assign(p,await PhotoTools.stamp(p.baseSrc,p.year,p.maxBytes||3000000))}
 async function save(){try{validate();setBusy(true);await syncPhotos();data.updated=new Date().toISOString().slice(0,10);const blob=new Blob(['window.SITE_CONTENT = '+JSON.stringify(data,null,2)+';\n'],{type:'text/javascript;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='content.js';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);dirty=false;$('#dirty').textContent='已导出';toast('已导出 content.js，请替换网站中的同名文件');return true}catch(e){toast(e.message);return false}finally{setBusy(false)}}
 function leave(){if(busy)return;if(dirty)$('#leave-dialog').showModal();else location.href='index.html'}
 $('#back').onclick=leave;$('#brand-back').onclick=e=>{e.preventDefault();leave()};$('#stay').onclick=()=>$('#leave-dialog').close();$('#discard').onclick=()=>{dirty=false;location.href='index.html'};$('#save-return').onclick=async()=>{if(await save())setTimeout(()=>location.href='index.html',300)};$('#save').onclick=save;
 $('#preview').onclick=async()=>{const win=window.open('about:blank','xiang-liu-preview');try{validate();setBusy(true);await syncPhotos();await new Promise((res,rej)=>{const r=indexedDB.open('xiang-liu-editor',1);r.onupgradeneeded=()=>r.result.createObjectStore('state');r.onerror=()=>rej(Error('无法打开预览存储'));r.onsuccess=()=>{const tx=r.result.transaction('state','readwrite');tx.objectStore('state').put(clone(data),'preview');tx.oncomplete=()=>{r.result.close();res()};tx.onerror=()=>rej(Error('预览存储失败'))}});if(win)win.location.href='index.html?preview=1';else toast('请允许预览弹窗')}catch(e){win?.close();toast(e.message)}finally{setBusy(false)}};
 document.addEventListener('input',e=>{const el=e.target;if(el.dataset.path)set(el.dataset.path,el.value);if(el.dataset.authors!==undefined){data.papers[Number(el.dataset.authors)].authors=el.value.split(/[,，\n]+/).map(s=>s.trim()).filter(Boolean).map(s=>({name:s.replace(/[*†‡]+$/,'').trim(),marks:(s.match(/[*†‡]+$/)||[''])[0]}));mark()}});
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||busy)return;if(b.dataset.tab){tab=b.dataset.tab;render()}if(b.dataset.photoLang){photoLang=b.dataset.photoLang;render()}if(b.dataset.add)addRecord(b.dataset.add);if(b.dataset.remove){const keys=b.dataset.remove.split('.'),i=Number(keys.pop());value(keys.join('.')).splice(i,1);mark();render()}if(b.dataset.move){const keys=b.dataset.move.split('.'),i=Number(keys.pop());move(keys.join('.'),i,Number(b.dataset.direction))}if(b.dataset.pin!==undefined){const p=data.papers[Number(b.dataset.pin)];p.pinned=!p.pinned;const peers=paperIndexes(p.first,p.pinned).filter(i=>i!==Number(b.dataset.pin));p.order=peers.length?Math.max(...peers.map(i=>data.papers[i].order))+1:0;mark();render()}if(b.dataset.photoPin!==undefined){const p=data.photos[Number(b.dataset.photoPin)];p.featured=!p.featured;if(p.featured){const orders=data.photos.filter(x=>x.featured&&Number.isFinite(x.featuredOrder)).map(x=>x.featuredOrder);p.featuredOrder=orders.length?Math.max(...orders)+1:0}else delete p.featuredOrder;mark();render()}if(b.dataset.addPaper!==undefined){data.papers.push({id:'paper-'+Date.now(),title:'',authors:[{name:'Xiang Liu',marks:'*'}],date:new Date().toISOString().slice(0,10),first:b.dataset.addPaper==='true',pinned:false,order:data.papers.length,summary:bi(),status:bi('预印本','Preprint'),arxiv:'',project:'',openreview:'',image:'',figure:bi('图 1 · 论文原图','FIG. 1 · FROM THE PAPER')});mark();render();const el=$(`[data-record="papers.${data.papers.length-1}"]`);el.querySelector('details').open=true;el.scrollIntoView({block:'center'})}if(b.id==='batch-delete'){data.photos=data.photos.filter(p=>!selected.has(p.id));selected.clear();mark();render();toast('选中照片已移除，保存导出后生效')}if(b.id==='batch-move'){$('#batch-fields').innerHTML=destination('move');$('#batch-dialog').showModal()}});
 document.addEventListener('change',async e=>{const el=e.target;if(el.dataset.first!==undefined){const p=data.papers[Number(el.dataset.first)];p.first=el.value==='true';p.order=data.papers.length;mark();render()}if(el.dataset.selectPhoto){if(el.checked)selected.add(el.dataset.selectPhoto);else selected.delete(el.dataset.selectPhoto);render()}if(el.dataset.selectGroup){el.dataset.selectGroup.split(',').forEach(i=>{if(el.checked)selected.add(data.photos[i].id);else selected.delete(data.photos[i].id)});render()}if(el.id==='select-all'){selected=el.checked?new Set(data.photos.map(p=>p.id)):new Set();render()}if(['upload-theme','move-theme'].includes(el.id)){const prefix=el.id.split('-')[0],g=el.value==='new'?{year:String(new Date().getFullYear()),theme:bi()}:groups()[Number(el.value)];$('#'+prefix+'-year').value=g.year;$('#'+prefix+'-zh').value=g.theme.zh;$('#'+prefix+'-en').value=g.theme.en}
 if(el.id==='photo-files'){let n=0;try{const dest=destinationValue('upload'),max=Number($('#photo-size').value),files=[...el.files];setBusy(true);el.disabled=true;for(const f of files){toast(`正在处理 ${n+1} / ${files.length}：${f.name}`);const image=await PhotoTools.prepare(f,max,dest.year),name=f.name.replace(/\.[^.]+$/,'');data.photos.push({id:'photo-'+Date.now()+'-'+n,...clone(dest),title:bi(name,name),alt:bi(name,name),featured:false,...image});n++;mark()}render();toast(`已添加 ${n} 张照片`)}catch(err){toast(`已添加 ${n} 张。${err.message}`);el.disabled=false}finally{setBusy(false)}}
 if(el.dataset.paperImage!==undefined&&el.files[0]){try{setBusy(true);data.papers[Number(el.dataset.paperImage)].image=(await PhotoTools.prepare(el.files[0],1000000)).src;mark();render()}catch(err){toast(err.message)}finally{setBusy(false)}}});
 $('#cancel-move').onclick=()=>$('#batch-dialog').close();$('#confirm-move').onclick=async()=>{const button=$('#confirm-move');try{const dest=destinationValue('move');button.disabled=true;setBusy(true);const changes=[];for(const p of data.photos.filter(p=>selected.has(p.id))){const patch={...clone(dest)};if(p.year!==dest.year&&p.baseSrc)Object.assign(patch,await PhotoTools.stamp(p.baseSrc,dest.year,p.maxBytes||3000000));changes.push([p,patch])}for(const [p,patch]of changes)Object.assign(p,patch);mark();selected.clear();$('#batch-dialog').close();render();toast('照片已移动，年份水印已同步更新')}catch(err){toast(err.message)}finally{button.disabled=false;setBusy(false)}};
 window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});render();
})();
