(() => {
 'use strict';
 const $ = s => document.querySelector(s), esc = x => String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const storage={get(k){try{return localStorage.getItem(k)}catch{return null}},set(k,v){try{localStorage.setItem(k,v)}catch{}}};
 let data=window.SITE_CONTENT,lang=storage.get('xl-language')==='en'?'en':'zh',slide=0,featuredSlide=0,paused=matchMedia('(prefers-reduced-motion: reduce)').matches,hover=false,route='',galleryKey='',gallerySort='default',galleryJump=false,timer,featuredTimer,likes={},likedPhotos=new Set();
 const t=x=>typeof x==='object'&&x!==null?(x[lang]||x.zh||x.en||''):x||'';
 const tr=(z,e)=>lang==='zh'?z:e;
 const safeUrl=(u,image=false)=>{u=String(u||'');if(image&&/^data:image\/(jpeg|png|webp);base64,/i.test(u))return u;if(image&&/^assets\/[a-zA-Z0-9_./-]+$/.test(u)&&!u.includes('..'))return u;try{const n=new URL(u);return ['https:','http:'].includes(n.protocol)?n.href:''}catch{return ''}};
 const visitorId=()=>{let id=storage.get('xl-visitor-id');if(id)return id;try{id=crypto.randomUUID()}catch{id='xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=crypto.getRandomValues(new Uint8Array(1))[0]&15;return(c==='x'?r:(r&3|8)).toString(16)})}storage.set('xl-visitor-id',id);return id};
 async function requestJson(endpoint,options={}){const controller=typeof AbortController==='function'?new AbortController():null,timer=controller?setTimeout(()=>controller.abort(),8000):null;try{const r=await fetch(endpoint,{...options,...(controller?{signal:controller.signal}:{})});if(!r.ok)throw Error(`HTTP ${r.status}`);return await r.json()}finally{if(timer)clearTimeout(timer)}}
 async function recordVisit(){const endpoint=safeUrl(data.stats?.visitEndpoint);if(!endpoint||location.protocol==='file:')return false;try{await requestJson(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId:visitorId()}),keepalive:true});return true}catch{return false}}
 async function loadStats(){const output=$('#visit-count'),endpoint=safeUrl(data.stats?.endpoint);if(!endpoint){if(output)output.textContent='—';return null}try{const j=await requestJson(endpoint);if(!Number.isSafeInteger(j.uniqueVisitors)||j.uniqueVisitors<0)throw Error();if(output)output.textContent=j.uniqueVisitors.toLocaleString();return j.uniqueVisitors}catch{if(output)output.textContent='—';return null}}
 async function loadLikes(){const endpoint=safeUrl(data.stats?.likesEndpoint);if(!endpoint||location.protocol==='file:')return;try{const j=await requestJson(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId:visitorId()})});likes=j.likes&&typeof j.likes==='object'?j.likes:{};likedPhotos=new Set(Array.isArray(j.liked)?j.liked:[]);if(route==='photography')render()}catch{}}
 async function likePhoto(id){const endpoint=safeUrl(data.stats?.likeEndpoint);if(!endpoint){toast(tr('爱心功能暂未连接','Likes are not connected yet'));return}const nextLiked=!likedPhotos.has(id);try{const j=await requestJson(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId:visitorId(),photoId:id,liked:nextLiked})});if(!Number.isSafeInteger(j.count)||j.count<0||typeof j.liked!=='boolean')throw Error();likes[id]=j.count;if(j.liked)likedPhotos.add(id);else likedPhotos.delete(id);document.querySelectorAll(`[data-like="${CSS.escape(id)}"]`).forEach(b=>{b.classList.toggle('liked',j.liked);b.setAttribute('aria-pressed',String(j.liked));b.setAttribute('aria-label',j.liked?tr('取消这张照片的爱心','Remove like from this photograph'):tr('为这张照片点爱心','Like this photograph'));b.querySelector('.heart').textContent=j.liked?'♥':'♡';b.querySelector('[data-like-count]').textContent=j.count.toLocaleString()});toast(j.liked?tr('谢谢你的爱心','Thank you for the love'):tr('已取消爱心','Like removed'))}catch{toast(tr('暂时无法更新爱心，请稍后重试','Unable to update the like right now'))}}
 const link=(u,label,cls='')=>safeUrl(u)?`<a href="${esc(safeUrl(u))}" target="_blank" rel="noopener noreferrer" class="${cls}">${esc(label)}</a>`:'';
 const authors=p=>p.authors.map(a=>`${a.name==='Xiang Liu'?'<strong>':''}${esc(a.name)}${a.name==='Xiang Liu'?'</strong>':''}${a.marks?`<sup>${esc(a.marks)}</sup>`:''}`).join(', ');
 const links=p=>`${link(p.project,'Project page ↗')}${link(p.arxiv,'arXiv ↗')}${p.openreview?link(p.openreview,'OpenReview ↗'):''}`;
 const primary=p=>p.project||p.arxiv||p.openreview;
 const sorted=first=>data.papers.filter(p=>p.first===first).sort((a,b)=>Number(!!b.pinned)-Number(!!a.pinned)||((a.order??0)-(b.order??0)));
 const heading=(n,z,e)=>`<div class="section-heading"><span class="num">${n}</span><h2>${tr(z,e)}</h2><span class="en">${e.toUpperCase()}</span></div>`;
 const certificateButton=h=>h.certificate?`<button class="certificate-button" data-certificate="${esc(safeUrl(h.certificate,true))}" data-caption="${esc(t(h.title))}" aria-label="${tr('查看证书：','View certificate: ')}${esc(t(h.title))}" aria-expanded="false"><span aria-hidden="true">▧</span><small>${tr('证书','CERT')}</small></button>`:'';

 const copyControl=v=>`<span class="copy-control"><button class="copy-text" data-copy="${esc(v)}">${esc(v)}</button><button class="copy-icon" data-copy="${esc(v)}" aria-label="${tr('复制','Copy')} ${esc(v)}" title="${tr('复制','Copy')}">⧉</button></span>`;
 const cameraMarkup=p=>{const c=p.camera||{};return `<span class="camera-meta"><span>${esc(c.focal||'—')}</span><span>ISO ${esc(c.iso||'—')}</span><span>S ${esc(c.shutter||'—')}</span><span>${esc(c.aperture||'f/—')}</span></span>`};
 const likeMarkup=p=>{const liked=likedPhotos.has(p.id);return `<button class="photo-like ${liked?'liked':''}" data-like="${esc(p.id)}" aria-label="${liked?tr('取消这张照片的爱心','Remove like from this photograph'):tr('为这张照片点爱心','Like this photograph')}" aria-pressed="${liked}"><span class="heart" aria-hidden="true">${liked?'♥':'♡'}</span><span data-like-count="${esc(p.id)}">${Number(likes[p.id]||0).toLocaleString()}</span></button>`};
 const downloadLink=p=>`<a class="photo-download" href="${esc(safeUrl(p.src,true))}" download="${esc(p.year+'-'+p.id+'.jpg')}" aria-label="${tr('下载照片','Download photo')}">↓ <span>${tr('下载','Download')}</span></a>`;
 function about(){const p=data.profile;slide=p.portraits.length?Math.min(slide,p.portraits.length-1):0;return `<section class="hero"><div><div class="eyebrow">WORLD MODELS · EMBODIED AI · PHOTOGRAPHY</div><h1>${esc(t(p.name))}${lang==='zh'?'<span>Xiang Liu</span>':''}</h1><p class="affiliation">${esc(t(p.affiliation))}</p><p class="muted" style="font-size:14px">${esc(t(p.degree))}</p><p class="hero-copy">${esc(t(p.intro))}</p><div class="tags">${p.tags.map(x=>`<span class="tag">${esc(t(x))}</span>`).join('')}</div><dl class="contact-grid"><div><dt>${tr('电话','Phone')}</dt><dd>${copyControl(p.phone)}</dd></div><div><dt>${tr('微信','WeChat')}</dt><dd>${copyControl(p.wechat)}</dd></div><div><dt>${tr('出生','Born')}</dt><dd>${esc(p.birth)}</dd></div><div><dt>GitHub</dt><dd>${link(p.github,'LiuJuzi1 ↗')}</dd></div><div style="grid-column:1/-1"><dt>${tr('邮箱','Email')}</dt><dd>${copyControl(p.email)}</dd></div></dl></div>${p.portraits.length?`<div class="portrait" aria-roledescription="carousel" aria-label="${tr('生活照片','Personal photos')}"><div class="portrait-frame"><img id="portrait-img" src="${esc(safeUrl(p.portraits[slide]||p.portraits[0],true))}" alt="${tr('刘翔的生活照片','A personal photograph of Xiang Liu')} ${slide+1}" fetchpriority="high"><span class="portrait-label">XIANG LIU / LIFE IN FRAMES</span><button class="slide-arrow prev" data-slide="-1" aria-label="${tr('上一张','Previous photo')}">◂</button><button class="slide-arrow next" data-slide="1" aria-label="${tr('下一张','Next photo')}">▸</button></div><div class="slide-controls"><button data-slide="-1" aria-label="${tr('上一张','Previous photo')}">◂</button>${p.portraits.map((_,i)=>`<button class="dot" data-index="${i}" aria-label="${tr('第','Photo ')}${i+1}${tr('张','')}" aria-pressed="${i===slide}"></button>`).join('')}<button data-slide="1" aria-label="${tr('下一张','Next photo')}">▸</button><button class="pause" id="slide-pause" aria-label="${tr('暂停自动播放','Pause slideshow')}">${paused?'▷':'Ⅱ'}</button></div></div>`:''}</section>
 <section class="section">${heading('01','个人经历','Experience')}<ol class="timeline">${data.experience.map(e=>`<li><div><strong>${esc(t(e.title))}</strong><div class="detail">${esc(t(e.detail))}</div></div><time>${esc(t(e.date))}</time></li>`).join('')}</ol></section>
 <section class="section">${heading('02','研究方向与导师','Research & Mentorship')}<p class="research-intro">${esc(t(p.research))}</p><div class="mentors">${data.mentors.map(m=>`<article class="mentor"><div class="role">${esc(t(m.role))}</div><h3>${link(m.url,t(m.name)+' ↗')}</h3><p>${esc(t(m.description))}</p></article>`).join('')}</div></section>
 <section class="section">${heading('03','部分荣誉与获奖','Honors & Awards')}<div class="honor-columns">${['graduate','undergraduate'].map((g,i)=>`<details class="honor-stage" ${i?'':'open'}><summary class="subheading">${i?tr('本科阶段','Undergraduate'):tr('硕士阶段','Graduate')}</summary><div class="honor-list">${data.honors[g].map(h=>`<article class="honor ${g==='undergraduate'?'honor-compact':''}"><time>${esc(h.date)}</time><div class="honor-copy"><strong>${esc(t(h.title))}</strong><p>${esc(t(h.detail))}</p>${h.team?`<p class="honor-team">${esc(t(h.team))}</p>`:''}</div>${certificateButton(h)}</article>`).join('')}</div></details>`).join('')}</div></section>
 <section class="section">${heading('04','论文列表','Publications')}${groups(false)}</section>`}
 function groups(detail){return [true,false].map((first,g)=>`<section class="publication-group"><h${detail?'2':'3'}>${first?tr('第一作者 / 共同第一作者','First / Co-first Author'):tr('合作论文 / 非第一作者','Collaborative Work / Contributing Author')} <span class="muted">· ${sorted(first).length}</span></h${detail?'2':'3'}>${sorted(first).map((p,i)=>detail?paper(p):`<article class="citation ${p.pinned?'pinned':''}"><span class="index">${String(i+1).padStart(2,'0')}${p.pinned?'<span class="pin-star" aria-label="Pinned">★</span>':''}</span><div><h4>${link(primary(p),p.title)}</h4><div class="authors">${authors(p)}</div><div class="status">${esc(t(p.status))}</div></div><div class="links">${links(p)}</div></article>`).join('')}</section>`).join('')}
 function paper(p){return `<article class="paper-card ${p.pinned?'pinned':''}"><div class="paper-art">${p.pinned?'<span class="paper-pin" aria-label="Pinned">★</span>':''}${p.image?`<button data-lightbox="${esc(safeUrl(p.image,true))}" data-caption="${esc(p.title)}" aria-label="${tr('放大论文图片','Enlarge paper figure')}"><img src="${esc(safeUrl(p.image,true))}" alt="${esc(p.title)} — ${esc(t(p.figure))}" loading="lazy"></button><div class="figure-label">${esc(t(p.figure))}</div>`:`<div class="paper-monogram">${esc(p.title.split(':')[0])}</div><div class="figure-label">${tr('方法图待补充','FIGURE TO BE ADDED')}</div>`}</div><div class="paper-content"><h3>${link(primary(p),p.title)}</h3><div class="authors">${authors(p)}</div><p class="abstract">${esc(t(p.summary))}</p><div class="paper-meta"><div class="status">${esc(t(p.status))}</div><div class="links">${links(p)}</div></div></div></article>`}
 function research(){return `<div class="page-heading"><div><div class="eyebrow">CHAPTER 02 / RESEARCH</div><h1>${tr('论文介绍','Research')}</h1></div><div class="legend">${tr('* 第一 / 共同第一作者','* First / co-first author')}<br>${tr('† 通讯作者　‡ 通讯作者兼项目负责人','† Corresponding author　‡ Corresponding author & project leader')}</div></div>${groups(true)}`}
 const defaultPhotoSort=(a,b)=>Number(!!a.portrait)-Number(!!b.portrait)||(a.order??0)-(b.order??0)||a._contentIndex-b._contentIndex;
 function normalizePhotoNames(){const groups=new Map();for(const [index,p]of data.photos.entries()){const key=p.year+'|'+p.theme.zh;if(!groups.has(key))groups.set(key,[]);groups.get(key).push({...p,_contentIndex:index})}for(const photos of groups.values()){photos.sort(defaultPhotoSort);const sequences=new Map();for(const photo of photos){const match=String(photo.title?.zh||'').match(/^(.* · )\d+$/);if(!match)continue;const n=(sequences.get(match[1])||0)+1,sequential=' · '+String(n).padStart(2,'0');sequences.set(match[1],n);for(const key of ['zh','en']){if(typeof photo.title?.[key]==='string')photo.title[key]=photo.title[key].replace(/ · \d+$/,sequential);if(typeof photo.alt?.[key]==='string')photo.alt[key]=photo.alt[key].replace(/ · \d+$/,sequential)}}}}
 function photoGroups(){const map=new Map();for(const [index,p] of data.photos.entries()){const key=p.year+'|'+p.theme.zh;if(!map.has(key))map.set(key,{year:p.year,theme:p.theme,photos:[]});map.get(key).photos.push({...p,_contentIndex:index})}for(const group of map.values())group.photos.sort((a,b)=>gallerySort==='likes'?Number(likes[b.id]||0)-Number(likes[a.id]||0)||defaultPhotoSort(a,b):defaultPhotoSort(a,b));return [...map].sort((a,b)=>b[1].year.localeCompare(a[1].year)||(a[1].theme.zh==='西藏风光'?-1:b[1].theme.zh==='西藏风光'?1:0))}
 const featuredPhotos=()=>data.photos.filter(p=>p.featured).sort((a,b)=>(a.featuredOrder??999)-(b.featuredOrder??999));
 const featuredPosition=(index,current,count)=>{let delta=(index-current+count)%count;if(delta>count/2)delta-=count;return delta===0?'current':delta===-1?'previous':delta===1?'next':delta<0?'before':'after'};
 function featuredCarousel(){const photos=featuredPhotos();if(!photos.length)return'';featuredSlide=(featuredSlide+photos.length)%photos.length;const p=photos[featuredSlide];return `<section class="featured-carousel" aria-label="${tr('置顶摄影作品轮播','Featured photography carousel')}"><div class="featured-heading"><span>${tr('精选作品','FEATURED WORKS')}</span><span>${String(featuredSlide+1).padStart(2,'0')} / ${String(photos.length).padStart(2,'0')}</span></div><figure class="featured-frame"><div class="featured-track">${photos.map((photo,i)=>`<button class="featured-card" data-featured-card="${i}" data-featured-position="${featuredPosition(i,featuredSlide,photos.length)}" ${i===featuredSlide?`data-lightbox="${esc(safeUrl(photo.src,true))}" data-caption="${esc(t(photo.title))}" data-photo-id="${esc(photo.id)}"`:''} aria-label="${i===featuredSlide?tr('放大当前精选作品','Enlarge current featured photograph'):i<featuredSlide?tr('查看上一张精选作品','Show previous featured photograph'):tr('查看下一张精选作品','Show next featured photograph')}"><img src="${esc(safeUrl(photo.src,true))}" alt="${esc(t(photo.alt))}" ${i===featuredSlide?'fetchpriority="high"':'loading="lazy"'}></button>`).join('')}</div><button class="featured-arrow featured-prev" data-featured-slide="-1" aria-label="${tr('上一张精选作品','Previous featured photograph')}">‹</button><button class="featured-arrow featured-next" data-featured-slide="1" aria-label="${tr('下一张精选作品','Next featured photograph')}">›</button><figcaption><span class="featured-title">${esc(t(p.title))}</span><span>${esc(p.year)} · ${esc(t(p.theme))}</span></figcaption></figure><div class="featured-dots">${photos.map((_,i)=>`<button data-featured-index="${i}" aria-label="${tr('查看第','Show featured photograph ')} ${i+1}" aria-pressed="${i===featuredSlide}"></button>`).join('')}</div></section>`}
 function showFeatured(index){const photos=featuredPhotos();if(!photos.length)return;featuredSlide=(index+photos.length)%photos.length;const p=photos[featuredSlide],frame=$('.featured-frame');if(!frame)return;frame.querySelectorAll('[data-featured-card]').forEach((b,i)=>{const current=i===featuredSlide;b.dataset.featuredPosition=featuredPosition(i,featuredSlide,photos.length);b.setAttribute('aria-label',current?tr('放大当前精选作品','Enlarge current featured photograph'):featuredPosition(i,featuredSlide,photos.length)==='previous'?tr('查看上一张精选作品','Show previous featured photograph'):tr('查看下一张精选作品','Show next featured photograph'));if(current){b.dataset.lightbox=safeUrl(photos[i].src,true);b.dataset.caption=t(photos[i].title);b.dataset.photoId=photos[i].id}else{delete b.dataset.lightbox;delete b.dataset.caption;delete b.dataset.photoId}});frame.querySelector('.featured-title').textContent=t(p.title);frame.querySelector('figcaption span:last-child').textContent=`${p.year} · ${t(p.theme)}`;$('.featured-heading span:last-child').textContent=`${String(featuredSlide+1).padStart(2,'0')} / ${String(photos.length).padStart(2,'0')}`;document.querySelectorAll('.featured-dots [data-featured-index]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.featuredIndex)===featuredSlide))}
 function scheduleFeatured(){clearTimeout(featuredTimer);if(route!=='photography')return;featuredTimer=setTimeout(()=>{if(route==='photography'&&!document.hidden&&!document.querySelector('dialog[open]'))showFeatured(featuredSlide+1);scheduleFeatured()},4800)}
 function photography(){const groups=photoGroups();if(!groups.length)return `<div class="page-heading"><h1>${tr('摄影作品集','Photography')}</h1></div><p class="empty">${tr('新的影像，正在路上。','New photographs are on the way.')}</p>`;if(!groups.some(([k])=>k===galleryKey))galleryKey=groups[0][0];let year='';const nav=groups.map(([k,g])=>{const y=year!==g.year?`<div class="gallery-year">${esc(g.year)}</div>`:'';year=g.year;return y+`<button data-gallery="${esc(k)}" class="${galleryKey===k?'active':''}" aria-current="${galleryKey===k?'true':'false'}">${esc(t(g.theme))}</button>`}).join('');const chosen=groups.find(([k])=>k===galleryKey)[1];return `<div class="page-heading photography-heading"><div><div class="eyebrow">CHAPTER 03 / PHOTOGRAPHY</div><h1>${tr('摄影作品集','Photography')}</h1></div><span class="muted" style="font-size:13px">@橘子掉了一地</span></div>${featuredCarousel()}<div class="gallery-layout"><aside class="gallery-nav" aria-label="${tr('摄影年份与主题','Photo years and themes')}">${nav}</aside><section><div class="gallery-title"><h2>${esc(t(chosen.theme))}</h2><div class="gallery-meta"><span>${chosen.year} · ${String(chosen.photos.length).padStart(2,'0')} ${tr('张作品','photographs')}</span><div class="sort-switch" role="group" aria-label="${tr('摄影作品排序','Photography sort')}"><button data-photo-sort="default" aria-pressed="${gallerySort==='default'}">${tr('默认排序','Default')}</button><button data-photo-sort="likes" aria-pressed="${gallerySort==='likes'}">${tr('按爱心数','Likes')}</button></div></div></div>${chosen.photos.map(p=>`<figure class="photo"><button data-lightbox="${esc(safeUrl(p.src,true))}" data-caption="${esc(t(p.title))}" data-photo-id="${esc(p.id)}"><img src="${esc(safeUrl(p.src,true))}" alt="${esc(t(p.alt))}" loading="lazy"></button><figcaption class="photo-caption">${cameraMarkup(p)}<span class="photo-name">${esc(t(p.title))}</span>${likeMarkup(p)}${downloadLink(p)}</figcaption></figure>`).join('')}</section></div>`}
 function showSlide(index){const count=data.profile.portraits.length;if(!count)return;slide=(index+count)%count;const img=$('#portrait-img');if(!img)return;img.src=safeUrl(data.profile.portraits[slide],true);img.alt=tr('刘翔的生活照片 ','A personal photograph of Xiang Liu ')+(slide+1);document.querySelectorAll('[data-index]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.index)===slide))}
 function render(reset=false){const hash=location.hash.slice(1).split('/');const next=['about','research','photography'].includes(hash[0])?hash[0]:'about';let key='';try{key=decodeURIComponent(hash.slice(1).join('/'))}catch{}if(key)galleryKey=key;const changed=route!==next;route=next;document.documentElement.lang=lang==='zh'?'zh-CN':'en';$('#main').innerHTML=route==='about'?about():route==='research'?research():photography();const labels=lang==='zh'?['基本信息','论文介绍','摄影作品集']:['About','Research','Photography'];document.querySelectorAll('[data-nav]').forEach((a,i)=>{a.textContent=labels[i];if(a.dataset.nav===route)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});$('#chapters').setAttribute('aria-label',tr('章节','Chapters'));$('#language').textContent=lang==='zh'?'EN':'中';$('#language').setAttribute('aria-label',tr('切换为英文','Switch to Chinese'));$('#visits').title=tr('浏览统计','Visitor statistics');$('#visits').setAttribute('aria-label',$('#visits').title);$('#manage').title=tr('内容管理','Content management');$('#manage').setAttribute('aria-label',$('#manage').title);$('#back-top').setAttribute('aria-label',tr('回到顶部','Back to top'));document.querySelectorAll('.dialog-close').forEach(b=>b.setAttribute('aria-label',tr('关闭','Close')));$('#footer').innerHTML=`<span>© ${new Date().getFullYear()} ${esc(t(data.profile.name))}</span><span>RESEARCH & LIFE / ${esc(data.updated.slice(0,7).replace('-','.'))}</span>`;document.title=tr('刘翔 · ','Xiang Liu · ')+labels[['about','research','photography'].indexOf(route)];const port=$('.portrait');if(port){port.addEventListener('mouseenter',()=>hover=true);port.addEventListener('mouseleave',()=>hover=false);port.addEventListener('focusin',()=>hover=true);port.addEventListener('focusout',e=>{if(!port.contains(e.relatedTarget))hover=false});let startX;port.addEventListener('touchstart',e=>startX=e.changedTouches[0].clientX,{passive:true});port.addEventListener('touchend',e=>{const delta=e.changedTouches[0].clientX-startX;if(Math.abs(delta)>40)showSlide(slide+(delta<0?1:-1))},{passive:true})}updateThemeLabel();if(reset||changed){window.scrollTo({top:0,behavior:'instant'});$('#back-top').hidden=true}}
 function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.remove('show'),3000)}
 function updateThemeLabel(){const dark=document.documentElement.dataset.theme==='dark';$('#theme').setAttribute('aria-label',dark?tr('切换浅色主题','Switch to light theme'):tr('切换深色主题','Switch to dark theme'));$('#theme').title=$('#theme').getAttribute('aria-label');$('#theme').textContent=dark?'☼':'◐'}
 document.documentElement.dataset.theme=storage.get('xl-theme')==='dark'?'dark':'light';
 $('#theme').onclick=()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';storage.set('xl-theme',document.documentElement.dataset.theme);updateThemeLabel()};
 $('#language').onclick=()=>{lang=lang==='zh'?'en':'zh';storage.set('xl-language',lang);render()};
 $('#back-top').onclick=()=>window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
 window.addEventListener('scroll',()=>$('#back-top').hidden=scrollY<350,{passive:true});
 window.addEventListener('hashchange',()=>{const jump=galleryJump;galleryJump=false;render(!jump);scheduleFeatured();if(jump)requestAnimationFrame(()=>$('.gallery-layout')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'}))});
 document.addEventListener('click',async e=>{
  const b=e.target.closest('button');if(!b)return;
  if(b.dataset.slide)showSlide(slide+Number(b.dataset.slide));
  if(b.dataset.index!==undefined)showSlide(Number(b.dataset.index));
  if(b.dataset.featuredCard!==undefined&&Number(b.dataset.featuredCard)!==featuredSlide){showFeatured(Number(b.dataset.featuredCard));scheduleFeatured();return}
  if(b.dataset.featuredSlide){showFeatured(featuredSlide+Number(b.dataset.featuredSlide));scheduleFeatured()}
  if(b.dataset.featuredIndex!==undefined){showFeatured(Number(b.dataset.featuredIndex));scheduleFeatured()}
  if(b.dataset.like)await likePhoto(b.dataset.like);
  if(b.id==='slide-pause'){paused=!paused;b.textContent=paused?'▷':'Ⅱ';b.setAttribute('aria-label',paused?tr('播放幻灯片','Play slideshow'):tr('暂停幻灯片','Pause slideshow'))}
  if(b.dataset.gallery){galleryKey=b.dataset.gallery;const nextHash='photography/'+encodeURIComponent(galleryKey);if(location.hash.slice(1)===nextHash){galleryJump=false;requestAnimationFrame(()=>$('.gallery-layout')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'}))}else{galleryJump=true;location.hash=nextHash}}
  if(b.dataset.photoSort){gallerySort=b.dataset.photoSort;render()}
  if(b.dataset.copy){try{await navigator.clipboard.writeText(b.dataset.copy);toast(tr('已复制','Copied'))}catch{const el=document.createElement('textarea');el.value=b.dataset.copy;el.style.cssText='position:fixed;opacity:0';document.body.append(el);el.select();const ok=document.execCommand('copy');el.remove();toast(ok?tr('已复制','Copied'):tr('复制失败，请手动复制','Copy failed; please copy manually'))}}
  if(b.dataset.lightbox){const d=$('#lightbox');d.querySelector('img').src=b.dataset.lightbox;d.querySelector('img').alt=b.dataset.caption;const photo=data.photos.find(p=>p.id===b.dataset.photoId);d.querySelector('.lightbox-caption').innerHTML=photo?`${cameraMarkup(photo)}<span class="photo-name">${esc(t(photo.title))}</span>${likeMarkup(photo)}${downloadLink(photo)}`:`<span></span><span class="photo-name">${esc(b.dataset.caption)}</span><span></span>`;d.showModal()}
 });
 document.addEventListener('click',e=>{const b=e.target.closest('button[data-certificate]');if(!b)return;const d=$('#lightbox'),img=d.querySelector('img'),same=d.open&&img.getAttribute('src')===b.dataset.certificate;document.querySelectorAll('.certificate-button').forEach(button=>button.setAttribute('aria-expanded','false'));if(same){d.close();return}img.src=b.dataset.certificate;img.alt=b.dataset.caption;d.querySelector('.lightbox-caption').innerHTML=`<button class="certificate-popup-toggle" data-certificate="${esc(b.dataset.certificate)}" data-caption="${esc(b.dataset.caption)}" aria-label="${tr('关闭证书','Close certificate')}"><span aria-hidden="true">▧</span> ${tr('证书','CERT')}</button><span class="photo-name">${esc(b.dataset.caption)}</span><span></span>`;b.setAttribute('aria-expanded','true');if(!d.open)d.showModal()});
 document.querySelectorAll('dialog').forEach(d=>{d.querySelector('.dialog-close').onclick=()=>d.close();d.addEventListener('close',()=>document.querySelectorAll('.certificate-button').forEach(button=>button.setAttribute('aria-expanded','false')));d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}})});
 $('#visits').onclick=async()=>{const el=$('#stats-body');el.innerHTML=`<div class="eyebrow">VISITOR STATISTICS</div><h2>${tr('历史浏览人数','Visitor history')}</h2><div class="stats-number">${esc($('#visit-count').textContent)}</div><p class="muted">${tr('正在读取统计…','Loading statistics…')}</p>`;$('#stats-dialog').showModal();const count=await loadStats();if(count===null){el.querySelector('p').textContent=tr('统计服务暂时不可用，请稍后重试。','Statistics are temporarily unavailable. Please try again later.');return}el.querySelector('.stats-number').textContent=count.toLocaleString();el.querySelector('p').textContent=tr('累计独立访客 · 匿名浏览器去重','Lifetime unique visitors · anonymous browser deduplication')};
 setInterval(()=>{if(route==='about'&&!paused&&!hover&&!document.hidden&&!document.querySelector('dialog[open]'))showSlide(slide+1)},5500);
 normalizePhotoNames();
 render();
 scheduleFeatured();
 loadStats();
 recordVisit().then(recorded=>{if(recorded)loadStats()});
 loadLikes();
 // Only an explicit editor preview reads local working content. Normal visitors always see content.js.
 if(new URLSearchParams(location.search).get('preview')==='1'){
  const req=indexedDB.open('xiang-liu-editor',1);req.onupgradeneeded=()=>req.result.createObjectStore('state');req.onsuccess=()=>{const q=req.result.transaction('state').objectStore('state').get('preview');q.onsuccess=()=>{if(q.result){data=q.result;slide=0;normalizePhotoNames();render();toast(tr('本地编辑预览，尚未发布','Local editor preview — not published'))}req.result.close()}};
 }
})();
