/* Local image processing. No images or EXIF data leave the browser. */
window.PhotoTools = (() => {
 const load = src => new Promise((resolve,reject)=>{const im=new Image();if(/^https?:/.test(src)&&new URL(src).origin!==location.origin)im.crossOrigin='anonymous';im.onload=()=>resolve(im);im.onerror=()=>reject(Error('无法读取图片'));im.src=src});
 const dataURL=blob=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(blob)});
 async function encode(canvas,max=3000000){for(let n=0;n<12;n++){for(const q of [.94,.90,.85,.79,.72]){const b=await new Promise(r=>canvas.toBlob(r,'image/jpeg',q));if(b&&b.size<max)return dataURL(b)}const c=document.createElement('canvas');c.width=Math.max(1,Math.round(canvas.width*.82));c.height=Math.max(1,Math.round(canvas.height*.82));c.getContext('2d').drawImage(canvas,0,0,c.width,c.height);canvas=c}throw Error('无法压缩到指定体积')}
 async function prepare(file,max=3000000,year=null){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('请选择 JPG / PNG / WebP 图片');if(file.size>120000000)throw Error('单张原图请小于 120 MB');const src=URL.createObjectURL(file);try{const im=await load(src),portrait=im.naturalHeight>im.naturalWidth,c=document.createElement('canvas'),scale=Math.min(1,2560/Math.max(im.naturalWidth,im.naturalHeight));c.width=Math.round(im.naturalWidth*scale);c.height=Math.round(im.naturalHeight*scale);const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(im,0,0,c.width,c.height);const imageSrc=await encode(c,max);if(year===null)return {src:imageSrc,portrait};return {src:imageSrc,maxBytes:max,portrait,camera:await exif(file)}}finally{URL.revokeObjectURL(src)}}
 async function exif(file){const empty={focal:'',iso:'',shutter:'',aperture:''};try{const b=await file.arrayBuffer(),v=new DataView(b);let tiff=-1;if(v.getUint16(0)===0xffd8){let p=2;while(p+4<v.byteLength){const marker=v.getUint16(p),len=v.getUint16(p+2);if(marker===0xffe1&&v.getUint32(p+4)===0x45786966){tiff=p+10;break}if(marker===0xffda||len<2)break;p+=2+len}}else if(v.getUint32(0)===0x89504e47){let p=8;while(p+12<v.byteLength){const n=v.getUint32(p);if(v.getUint32(p+4)===0x65584966){tiff=p+8;break}p+=12+n}}if(tiff<0)return empty;const le=v.getUint16(tiff)===0x4949,u16=p=>v.getUint16(p,le),u32=p=>v.getUint32(p,le),tags={};function ifd(offset,depth=0){if(depth>2)return;const p=tiff+offset,n=Math.min(u16(p),500);for(let i=0;i<n;i++){const e=p+2+i*12,tag=u16(e),type=u16(e+2),count=u32(e+4);let val;const size=({1:1,2:1,3:2,4:4,5:8,7:1,9:4,10:8})[type]||1;const pos=count*size<=4?e+8:tiff+u32(e+8);if(type===3)val=u16(pos);if(type===4)val=u32(pos);if(type===5)val=u32(pos)/u32(pos+4);if(tag===0x8769&&val)ifd(val,depth+1);else if(val!==undefined)tags[tag]=val}}ifd(u32(tiff+4));const n=x=>Number(Number(x).toFixed(2)).toString();return {focal:tags[37386]?n(tags[37386])+' mm':'',iso:tags[34855]?String(tags[34855]):'',shutter:tags[33434]?(tags[33434]<1?'1/'+Math.round(1/tags[33434])+' s':n(tags[33434])+' s'):'',aperture:tags[33437]?'f/'+n(tags[33437]):''}}catch{return empty}}
 return {prepare,exif};
})();
